services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
